name: pupil-recording-interface
channels:
  - conda-forge
  - phausamann
dependencies:
  # scientific stack
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  # video
  - ffmpeg=4.1.3
  - x264=1!152.20180806
  - opencv=4.1.0
  # pupil
  - libusb=1.0.23
  - libuvc=0.0.7
  - libjpeg-turbo=2.0.3
  - pyuvc=0.13
  - msgpack-python=0.6.2
  # realsense
  - librealsense2=2.32.1
  # other
  - tqdm
  # development
  - pytest
  - coverage
  - flake8
  - black
  - sphinx==1.8.5
  - sphinx_rtd_theme
  - numpydoc
  - matplotlib
  # pip
  - pip:
    - opencv-python==4.1.0.25 # reinstall through pip because cli breaks otherwise
    - pyrealsense2
