name: pri
channels:
  - conda-forge
  - loopbio
  - phausamann
dependencies:
  - python=3.6
  - pip=20.1
  # scientific stack
  - numpy=1.18
  - pandas=1.0
  - xarray=0.15
  - scipy=1.4
  # video
  - opencv=4.2.0
  - ffmpeg=3.4.2=x265_0
  - av=6.2.0
  - x264=1!152.20180806
  - x265=2.8
  # pupil
  - libusb=1.0.23
  - libuvc=0.0.7
  - libjpeg-turbo=2.0.3
  - pyuvc=0.13
  - msgpack-python=0.6.2
  - pupil-detectors=1.0.5
  # realsense
  - librealsense2=2.36.0
  # flir
  - spinnaker-sdk=1.27.0.48
  - pyspin=1.27.0.48
  # other
  - tqdm=4.46.0
  - matplotlib=3.1.1
  # development
  - pytest
  - coverage
  - flake8=3.7.9
  - black=19.10b0
  - pre_commit
  - sphinx=2.4.4
  - sphinx_rtd_theme
  - numpydoc
  - sphinx-gallery
  - matplotlib
  - bump2version
  # pip
  - pip:
    - netcdf4==1.5.3
    - pyrealsense2==2.36.0.2038
    - simple-pyspin==0.1.1
    - sphinx-multiversion
