name: pupil-recording-interface
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - xarray
  - opencv
  - netcdf4
  - msgpack-python
  - tqdm
  - monotonic
  - pip:
    - opencv-python # reinstall through pip because cli breaks otherwise
    - pyrealsense2
