name: pupil-recording-interface
channels:
  - conda-forge
  - eyeware
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - pandas
  - xarray
  - librealsense2
  - ffmpeg=4.1.3
  - x264=1!152.20180806
  - opencv=4.1.0
  - netcdf4
  - msgpack-python=0.6.2
  - tqdm
  # dev requirements
  - pytest
  - coverage
  - flake8
  - black
  - sphinx==1.8.5
  - sphinx_rtd_theme
  - numpydoc
  - matplotlib
  - pip:
    - opencv-python==4.1.0.25 # reinstall through pip because cli breaks otherwise
    - pyrealsense2
    - git+https://github.com/pupil-labs/pyuvc.git
