name: pri
channels:
  - conda-forge
  - phausamann
dependencies:
  - python=3.6
  - pip
  # scientific stack
  - numpy=1.18
  - pandas=1.0
  - xarray=0.15
  - scipy=1.4
  - netcdf4=1.5
  # video
  - ffmpeg=4.1.3
  - x264=1!152.20180806
  # pupil
  - libusb=1.0.23
  - libuvc=0.0.7
  - libjpeg-turbo=2.0.3
  - pyuvc=0.13
  - msgpack-python=0.6.2
  - cython=0.29.16
  - cysignals=1.10.2
  # realsense
  - librealsense2=2.32.1
  # flir
  - pyspin=1.27.0.48
  # other
  - tqdm
  # development
  - pytest
  - coverage
  - flake8
  - black
  - pre_commit
  - sphinx=1.8.5
  - sphinx_rtd_theme
  - numpydoc
  - matplotlib
  # pip
  - pip:
    - opencv-python==4.1.0.25
    - pupil-detectors==1.0.4
    - pyrealsense2
