{% set data = load_setup_py_data() %}

package:
  name: pupil_recording_interface
  version: {{ data['version'] }}

source:
  path: ../..

build:
  noarch: python
  number: 0
  ignore_run_exports:
    - python_abi

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy
    - pandas
    - xarray >=0.15
    - scipy
    - msgpack-python<1.0
    - opencv

test:
  source_files:
    - tests
  requires:
    - python 3.6
    - netcdf4
    - pooch
    - pytest
    - pytest-cov
  commands:
    - pytest --cov=pupil_recording_interface

about:
  home: https://github.com/vedb/pupil_recording_interface
  summary: A pythonic interface for the Pupil Core system.

extra:
  recipe-maintainers:
    - phausamann
