name: build

on: [push]

jobs:

  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --ignore=E203,W503,W504 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

  black:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Check black code style
      run: |
        pip install black
        black --check .

  docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies and package
      run: |
        pip install -r requirements.txt -r requirements_dev.txt
        pip install .
    - name: Build Sphinx docs and run doctests
      run: |
        make -C docs/ html
        make -C docs/ doctest
    - if: success() && github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target_branch: gh-pages
        build_dir: docs/_build/html/
