name: build

on: [push]

jobs:

  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements_dev.txt
      - name: Lint with flake8
        run: |
          flake8 pupil_recording_interface tests --ignore=E203,W503,W504 --exclude=**/externals
      - name: Install package
        run: python setup.py install
      - name: Test with pytest
        run: |
          pytest

  conda:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
      - name: Check versions
        run: |
          conda --version
          which python
      - name: Create environment
        run: |
          conda install -y -c conda-forge mamba
          mamba env create
      - name: Install package
        run: |
          source activate pri
          pip install --no-deps .
      - name: Test with pytest
        run: |
          source activate pri
          pytest

  conda-minimal:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
      - name: Check versions
        run: |
          conda --version
          which python
      - name: Create environment
        run: |
          conda install -y -c conda-forge mamba
          mamba create -y -n pri python=3.6 xarray scipy opencv "msgpack-python<1.0"
      - name: Install package
        run: |
          source activate pri
          pip install --no-deps .
      - name: Test with pytest
        run: |
          source activate pri
          conda install pytest
          pytest

  conda-build:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
      - name: Check versions
        run: |
          conda --version
          which python
      - name: Set up build system
        run: |
          conda install -y -c conda-forge boa anaconda-client
          conda config --set anaconda_upload no
      - name: Run conda build
        run: conda mambabuild -f build_tools/conda_recipe
      - name: Upload to channel (on tags)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u phausamann ~/conda-bld/noarch/pupil_recording_interface*.tar.bz2 --force

  docs:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
      - name: Check versions
        run: |
          conda --version
          which python
      - name: Create environment
        run: |
          conda install -y -c conda-forge mamba
          mamba env create
      - name: Install package
        run: |
          source activate pri
          pip install --no-deps .
      - name: Build Sphinx docs and run doctests
        run: |
          source activate pri
          make -C docs/ html
          make -C docs/ doctest

  docs-multiversion:
    # runs on pushes to master and devel but is always built against the
    # package from the master branch to avoid broken docs for master
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/devel'
    steps:
      - uses: actions/checkout@v2
      - name: Fetch branches and tags
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git checkout devel
          git checkout master
      - uses: s-weigand/setup-conda@v1
      - name: Check versions
        run: |
          conda --version
          which python
      - name: Create environment
        run: |
          conda install -y -c conda-forge mamba
          mamba env create
      - name: Install package
        run: |
          source activate pri
          pip install --no-deps .
      - name: Build Sphinx multiversion docs
        run: |
          source activate pri
          sphinx-multiversion docs docs/_build/html
          cp docs/index.html docs/_build/html
          touch docs/_build/html/.nojekyll
      - name: Deploy docs
        run: |
          sudo mkdir /docs -m 777
          mv docs/_build/html/* /docs
          git config user.name CI
          git config user.email ""
          git checkout -f --orphan privpage
          git rm --cached -rfq .
          git clean -fxdq
          mv /docs/* .
          git add .
          git commit -qm "Update docs"
          git push -f --set-upstream origin privpage

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Check black code style
        run: |
          pip install black==19.10b0
          black --check .
